-- SQLite
CREATE TABLE tbcadast_cooperado (
    ID INTEGER PRIMARY KEY, 
    COOPERATIVA INTEGER NOT NULL, 
    CONTA INTEGER NOT NULL, 
    NOME TEXT NOT NULL
);

CREATE TABLE tbcadast_critica (
    ID INTEGER PRIMARY KEY,
    CODIGOCRITICA INTEGER NOT NULL,
    DESCRICAOCRITICA TEXT NOT NULL
);

CREATE TABLE tbemprestimo_contrato (
    ID INTEGER PRIMARY KEY,
    IDCONTRATO INTEGER,
    IDCRITICA INTEGER,
    CONTRATO INTEGER NOT NULL,
    VALOR REAL NOT NULL,
    DATACONTRATACAO TEXT NOT NULL,
    FOREIGN KEY (IDCONTRATO)
       REFERENCES tbcadast_cooperado (ID),
    FOREIGN KEY (IDCRITICA)
       REFERENCES tbcadast_critica (ID)
);